# Generated by Django 5.0.1 on 2024-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
